apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: openrouter-model
spec:
  apiKeySecret: openrouterkey
  apiKeySecretKey: apiKey
  model: gpt-4o-mini
  provider: OpenAI
  openAI: {}
